#!/usr/bin/env bash
# Prints ready-to-paste secret env vars for .env.
#
# Usage:
#   ./scripts/gen-secrets.sh              # print to stdout
#   ./scripts/gen-secrets.sh >> .env      # append to your .env
set -euo pipefail

# Fernet requires a 32-byte urlsafe-base64 key. `openssl rand -base64 32`
# produces 32 raw bytes base64-encoded; swap the alphabet to urlsafe.
fernet_key() {
  openssl rand -base64 32 | tr '+/' '-_'
}

# n8n's encryption key just needs to be a long random string.
random_hex() {
  openssl rand -hex 32
}

echo "# Generated by scripts/gen-secrets.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
echo "APP_ENCRYPTION_KEY=$(fernet_key)"
echo "N8N_ENCRYPTION_KEY=$(random_hex)"
echo "SETUP_TOKEN=$(random_hex)"
